### ISSUE TITLE
Provide mouse and keyboard controls

### ISSUE THREAD

**Issue by ahmadtibi** [vazgriz/FlightSim#1]
Hello, could you by any chance provide mouse and keyboard controls for steering the jet? I tried to play around but I couldn't add mouse control to steer the jet. Thanks.

**Comment by MachXNU** [comment]
You can add controls in the Input System located inside the Assets folder.
There are plenty of tutorials online about how to add controls schemes to the new Input System.

**Comment by vazgriz** [comment]
This feature will not be added
